sudo: false

services:
  - docker
  
script:
  - echo "1 Step ##########################"
  - scripts/./enter.sh
  - echo 'make -C /build/buildroot BR2_EXTERNAL=/build/buildroot-external defconfig BR2_DEFCONFIG=/build/buildroot-external/configs/xy_defconfig'
  - echo 'exit'
  - ls -la
after_script:
  - echo "4 Step ##########################"
  - ./getimage.sh
